<a href="https://colab.research.google.com/github/GUNAPILLCO/neural_profit/blob/main/3_dataset_preparation/3_1_split_train_valid_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 3_1_split_train_valid_test

## Introducción

## 0. Configuración del Entorno

### 0.1. Clonado de repositorio / Acceso a Drive

In [1]:
#Clonamos el repo
#LINK DE REPOSITORIO: https://github.com/GUNAPILLCO/neural_profit
!git clone https://github.com/GUNAPILLCO/neural_profit.git

Cloning into 'neural_profit'...
remote: Enumerating objects: 526, done.
remote: Counting objects: 100% (146/146), done.
remote: Compressing objects: 100% (122/122), done.
remote: Total 526 (delta 92), reused 37 (delta 24), pack-reused 380 (from 2)
Receiving objects: 100% (526/526), 250.28 MiB | 18.33 MiB/s, done.
Resolving deltas: 100% (307/307), done.
Updating files: 100% (61/61), done.

In [2]:
from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/neural_profit"

Mounted at /content/drive

### 0.2. Instalación de librerías

In [3]:
#!{sys.executable} -m pip install -q ta
#print("Librería instalada: technical-analysis")

### 0.3. Importación de librerías

In [4]:
import sys
import re
#Instalación de librería pandas_market_calendars
#!{sys.executable} -m pip install -q pandas_market_calendars
#print("Librería instalada: pandas_market_calendars")


from functools import reduce
# Utilidades generales
from datetime import datetime, timedelta
import os
import glob
import requests
import warnings
warnings.filterwarnings('ignore')

# Manejo y procesamiento de datos
#import ta
import pandas as pd
import numpy as np
from tabulate import tabulate
import matplotlib.pyplot as plt
# Calendario de mercados
#import pandas_market_calendars as mcal

#from ta.momentum import StochasticOscillator, ROCIndicator
#from ta.volatility import BollingerBands, AverageTrueRange

from scipy.stats import spearmanr

## 1. Carga de datos

### 1.1. Carga de dataset MNQ_to_model

In [19]:
def load_data(data: str):

    data_path = f'{drive_path}/2_feature_engineering/mnq_{data}.parquet'
    # Leer el archivo Parquet y cargarlo en un DataFrame
    df = pd.read_parquet(data_path)

    # Asegurar que el índice esté en formato datetime
    df.index = pd.to_datetime(df.index)

    # Crear una nueva columna 'date' con la fecha extraída del índice
    df['date'] = df.index.date

    # Reordenar columnas: 'date', 'time_str', y luego el resto
    cols = ['date'] + [col for col in df.columns if col not in ['date']]

    df = df[cols]

    return df

In [20]:
mnq_model = load_data("to_model")

In [21]:
mnq_model

,date,open,high,low,close,volume,target_return_30,target_return_60,target_return_90,bb_60,ire_60,ire_90,momentum_5,price_ema30,rev_mom_vol_z_60,rev_mom_z_90,rev_score_90,roc_20,roc_60
datetime,,,,,,,,,,,,,,,,,,,
2019-12-23 08:00:00-05:00,2019-12-23,8734.00,8734.25,8733.75,8733.75,31,0.000372,0.000401,-0.000057,NaN,NaN,NaN,NaN,0.000000e+00,NaN,NaN,NaN,NaN,NaN
2019-12-23 08:01:00-05:00,2019-12-23,8734.00,8734.25,8733.75,8734.00,16,0.000286,0.000458,-0.000515,NaN,NaN,NaN,NaN,1.383501e-05,NaN,NaN,0.923157,NaN,NaN
2019-12-23 08:02:00-05:00,2019-12-23,8734.00,8734.00,8733.25,8733.25,23,0.000315,0.000544,-0.000831,NaN,NaN,NaN,NaN,-4.640816e-05,NaN,NaN,-0.750224,NaN,NaN
2019-12-23 08:03:00-05:00,2019-12-23,8734.25,8734.50,8734.00,8734.00,23,0.000315,0.000429,-0.000630,NaN,NaN,NaN,NaN,2.859176e-05,NaN,NaN,0.791723,NaN,NaN
2019-12-23 08:04:00-05:00,2019-12-23,8734.00,8734.00,8733.50,8733.75,12,0.000458,0.000429,-0.000630,NaN,NaN,NaN,NaN,-2.535945e-08,NaN,NaN,0.206907,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-06-13 15:56:00-04:00,2025-06-13,21624.50,21635.00,21613.50,21617.50,3251,NaN,NaN,NaN,0.100025,-1.641428,-1.773812,-0.000947,-8.844700e-04,0.518554,1.039346,-0.869941,-0.073959,-0.203125
2025-06-13 15:57:00-04:00,2025-06-13,21616.50,21635.25,21615.75,21623.75,2201,NaN,NaN,NaN,0.191181,-1.553505,-1.683865,-0.000474,-5.572032e-04,0.300185,0.747743,-0.649621,-0.156988,-0.182336
2025-06-13 15:58:00-04:00,2025-06-13,21623.25,21632.75,21616.50,21621.75,1859,NaN,NaN,NaN,0.175104,-1.581640,-1.712648,-0.000035,-6.077556e-04,0.122607,0.563217,-0.704523,-0.219205,-0.102800
2025-06-13 15:59:00-04:00,2025-06-13,21622.00,21632.25,21618.00,21628.00,2695,NaN,NaN,NaN,0.259627,-1.493717,-1.622701,0.000578,-2.983043e-04,0.175433,0.520225,-0.468363,-0.171934,-0.094695
2025-06-13 16:00:00-04:00,2025-06-13,21627.75,21656.25,21622.50,21651.75,6507,NaN,NaN,NaN,0.558977,-1.159609,-1.280902,0.001260,7.478636e-04,0.372312,0.193235,0.408903,-0.043857,-0.077301

### 1.2. Información de dataset MNQ_to_model

In [22]:
def info_dataset(df):
  print("Información del dataset:\n")

  # Contar valores únicos en la columna 'date'
  num_dias = df['date'].nunique()
  print(f"\tCantidad de días: {num_dias}")

  # Filtrar valores válidos
  validos_por_dia = df.dropna(subset=['close']).groupby('date').size()

  # Calcular el promedio
  promedio_por_fecha = validos_por_dia.mean()
  print(f"\tRegistros por día: {int(promedio_por_fecha)}")

  primer_hora = df.index[0].strftime('%H:%M')
  ultima_hora = df.index[-1].strftime('%H:%M')
  zona_horaria = df.index[0].tzinfo


  print(f"\tHora diaria de inicio {primer_hora}")
  print(f"\tHora diaria de final {ultima_hora}")
  print(f"\tZona horaria: {zona_horaria}")

  return num_dias, promedio_por_fecha

In [23]:
num_dias, promedio_por_fecha = info_dataset(mnq_model)

Información del dataset:

	Cantidad de días: 1311
	Registros por día: 481
	Hora diaria de inicio 08:00
	Hora diaria de final 16:00
	Zona horaria: America/New_York

### 1.3. Carga de listado de features por ventana de tiempo

In [24]:
import json

# Ruta al archivo guardado
path = f'{drive_path}/2_feature_engineering/features_list.json'

with open(path, "r") as f:
    features_dict = json.load(f)

# Extraer las listas
features_to_30 = features_dict["features_to_30"]
features_to_60 = features_dict["features_to_60"]
features_to_90 = features_dict["features_to_90"]

In [26]:
print(f'Listado de features para 30min: {features_to_30}')
print(f'Listado de features para 60min: {features_to_60}')
print(f'Listado de features para 90min: {features_to_90}')

Listado de features para 30min: ['ire_90', 'rev_mom_z_90', 'roc_60', 'rev_score_90', 'price_ema30']
Listado de features para 60min: ['ire_60', 'rev_mom_z_90', 'roc_60', 'bb_60', 'rev_mom_vol_z_60', 'momentum_5', 'roc_20']
Listado de features para 90min: ['ire_60', 'rev_mom_z_90', 'roc_60', 'bb_60', 'momentum_5', 'roc_20', 'rev_mom_vol_z_60']

## 2. Análisis detallado del dataset mnq_model

### 2.1. Búsqueda de NaN:

Buscamos los valores NaN en todas la columnas del dataset:

In [50]:
# Contar NaN por día y por columna
daily_nan_counts = mnq_model.groupby("date").apply(lambda x: x.isna().sum())

# Construir DataFrame con los valores únicos
daily_unique_nans = pd.DataFrame({
    "feature": daily_nan_counts.columns,
    "daily_nan_counts": [sorted(daily_nan_counts[col].unique()) for col in daily_nan_counts.columns]
})

In [51]:
daily_unique_nans

             feature daily_nan_counts
0               date              [0]
1               open              [0]
2               high              [0]
3                low              [0]
4              close              [0]
5             volume              [0]
6   target_return_30             [30]
7   target_return_60             [60]
8   target_return_90             [90]
9              bb_60             [59]
10            ire_60             [60]
11            ire_90             [90]
12        momentum_5              [5]
13       price_ema30              [0]
14  rev_mom_vol_z_60             [60]
15      rev_mom_z_90             [90]
16      rev_score_90        [1, 2, 3]
17            roc_20             [20]
18            roc_60             [60]

Lo que se observa es:

- OHLCV y date → [0] → nunca tienen valores faltantes.

- Targets (target_return_*) → [30], [60], [90] → todos los días tienen esos NaN al final, consistente con la ventana de predicción que corta datos futuros.

- Factores técnicos → muchos muestran valores únicos iguales al tamaño de la ventana usada en su cálculo:

  - bb_60 → [59] → se necesitan 60 valores para calcular, por eso hay 59 NaN iniciales cada día.
  - ire_60, roc_60, rev_mom_vol_z_60 → [60].
  - ire_90, rev_mom_z_90 → [90].
  - roc_20 → [20].
  - momentum_5 → [5].

Caso particular:

- rev_score_90 → [1, 2, 3] → parece que en algunos días puede generar hasta 3 NaN, pero no es fijo como los demás.

Las ventanas más grandes con valores NaN son la `ire_90` y `rev_mom_z_90` que necesitan 90 minutos de historial.

Vamos a filtrar el dataset `mnq_model` para eliminar todos los NaNs:

In [62]:
# Filtrar filas sin NaN en ninguna columna
mnq_model_clean = mnq_model.dropna(how="any")

In [63]:
num_dias, promedio_por_fecha = info_dataset(mnq_model_clean)

Información del dataset:

	Cantidad de días: 1311
	Registros por día: 301
	Hora diaria de inicio 09:30
	Hora diaria de final 14:30
	Zona horaria: America/New_York

Como se observa en el resultado, el primer registro válido (sin valores NaN en ninguna columna) aparece a las 09:30 y la jornada finaliza a las 14:30.

A continuación, verificamos en el dataset filtrado si existen saltos en la secuencia temporal o si todos los registros se mantienen consecutivos.

#### Función para detectar saltos temporales

In [60]:
def detectar_gaps(df: pd.DataFrame, gap_minutes: int = 1):
    """
    Verifica si existen saltos mayores al intervalo esperado (por defecto 1 minuto)
    entre registros consecutivos dentro de cada día, en un DataFrame con índice tipo DatetimeIndex.

    Omite el primer registro de cada día.

    Parámetros:
    - df: DataFrame con índice datetime.
    - gap_minutes: tamaño esperado del intervalo en minutos (por defecto 1).

    Retorna:
    - Lista de índices donde se detectaron diferencias mayores al intervalo esperado.
    """
    df = df.copy()
    df['time_diff'] = df.index.to_series().diff()

    base_time_diff = pd.Timedelta(minutes=gap_minutes)
    problem_indices = []

    for date, group in df.groupby(df.index.date):
        time_diff = group['time_diff'].iloc[1:]
        incorrect_indices = time_diff[time_diff != base_time_diff].index
        if len(incorrect_indices) > 0:
            problem_indices.append(incorrect_indices)

    if problem_indices:
        print(f"Se encontraron problemas en {len(problem_indices)} registros con diferencias irregulares.\n")

        # Conteo por fecha
        conteos = df.groupby(df.index.date).size()

        for i in range(len(problem_indices)):
            idx = problem_indices[i][0]
            diff = df.loc[idx, 'time_diff']
            date = idx.date()
            count = conteos[date]
            print(f'\t{idx} -> Diferencia: {diff} | # Registros: {count}')
    else:
        print("No se encontraron problemas, todas las muestras son consecutivas minuto a minuto.")

    return problem_indices

#### Resultados

In [64]:
detectar_gaps(mnq_model_clean)

No se encontraron problemas, todas las muestras son consecutivas minuto a minuto.

[]

## 2. Definición de tamaños

Definimos la cantidad de días para los sets de entrenamiento, testeo y validación

In [54]:
longitud_train = int(num_dias * 0.7)
print(f'Tamaño dataset train: {longitud_train} días')

longitud_valid = int((num_dias-longitud_train)/2)
print(f'Tamaño dataset valid: {longitud_valid} días')

longitud_test = int((num_dias-longitud_train)/2)
print(f'Tamaño dataset test: {longitud_test} días')

Tamaño dataset train: 917 días
Tamaño dataset valid: 197 días
Tamaño dataset test: 197 días

## 3. Aleatoriedad de días

In [27]:
# Obtener días únicos
unique_days = mnq_model['date'].unique()
np.random.seed(42)  # Reproducibilidad
np.random.shuffle(unique_days)  # Mezcla aleatoria

# Definir tamaños
n_train, n_val, n_test = 917, 197, 197

# Dividir días
train_days = unique_days[:n_train]
val_days = unique_days[n_train:n_train + n_val]
test_days = unique_days[n_train + n_val:n_train + n_val + n_test]

# Crear datasets
mnq_train = mnq_model[mnq_model['date'].isin(train_days)].copy()
mnq_valid = mnq_model[mnq_model['date'].isin(val_days)].copy()
mnq_test = mnq_model[mnq_model['date'].isin(test_days)].copy()

# Verificación
print("Train:", mnq_train['date'].nunique(), "días -", mnq_train.shape)
print("Val:  ", mnq_valid['date'].nunique(), "días -", mnq_valid.shape)
print("Test: ", mnq_test['date'].nunique(), "días -", mnq_test.shape)

Train: 917 días - (441077, 19)
Val:   197 días - (94757, 19)
Test:  197 días - (94757, 19)

### Guardamos los datasets

In [ ]:
#Guardamos el dataset
ruta_mnq_train = '/content/neural_profit/3_diseño_entrenamiento_evaluacion/mnq_train.parquet'
mnq_train.to_parquet(ruta_mnq_train, index=True)

ruta_mnq_valid = '/content/neural_profit/3_diseño_entrenamiento_evaluacion/mnq_valid.parquet'
mnq_valid.to_parquet(ruta_mnq_valid, index=True)

ruta_mnq_test = '/content/neural_profit/3_diseño_entrenamiento_evaluacion/mnq_test.parquet'
mnq_test.to_parquet(ruta_mnq_test, index=True)

In [ ]:
#Cambiamos de directorio
%cd neural_profit

/content/neural_profit

In [ ]:
token = "" #busca el archivo token en D:\Escritorio\UBA-CEIA\token_neural_profit
!git config --global user.email "gusunapillco@gmail.com"
!git config --global user.name "GUNAPILLCO"
!git add .
!git commit -m "Datasets train, valid y test generados desde colab "
!git push https://GUNAPILLCO:{token}@github.com/GUNAPILLCO/neural_profit.git

print("Dataset guardados correctamente")

[main f30c9ab] Datasets train, valid y test generados desde colab
 3 files changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 "3_dise\303\261o_entrenamiento_evaluacion/mnq_test.parquet"
 create mode 100644 "3_dise\303\261o_entrenamiento_evaluacion/mnq_train.parquet"
 create mode 100644 "3_dise\303\261o_entrenamiento_evaluacion/mnq_valid.parquet"
Enumerating objects: 8, done.
Counting objects: 100% (8/8), done.
Delta compression using up to 2 threads
Compressing objects: 100% (6/6), done.
Writing objects: 100% (6/6), 69.66 MiB | 10.07 MiB/s, done.
Total 6 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
remote: warning: See https://gh.io/lfs for more information.
remote: warning: File 3_diseño_entrenamiento_evaluacion/mnq_train.parquet is 51.84 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/GUNAPILLCO/neural_profit.git
   aeef5ff..f30c9ab  main -> main
Dataset guardados correctamente