<a href="https://colab.research.google.com/github/GUNAPILLCO/neural_profit/blob/main/6_catboost_model/6_1_baseline_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **6_1_baseline_model**

## Introducción y Resumen

CatBoost (Categorical Boosting) es un algoritmo de gradient boosting sobre árboles de decisión, diseñado para ofrecer alto rendimiento predictivo con mínima necesidad de preprocesamiento. Se caracteriza por una implementación robusta frente al overfitting, estabilidad en datasets ruidosos y una buena capacidad para capturar relaciones no lineales entre variables.

A diferencia de otros métodos de boosting, CatBoost incorpora técnicas internas que reducen el sesgo en el entrenamiento y mejoran la generalización, lo que lo hace especialmente adecuado para problemas de series temporales transformadas en features tabulares, como nuestro caso con datos intradía.

**Aplicación al horizonte de 90 minutos**

En el contexto de nuestro proyecto, CatBoost se utilizará para predecir el retorno acumulado a 90 minutos, a partir de:

- Ventanas deslizantes de datos intradía (OHLCV).
- Factores técnicos y alpha factors ya ingenierizados.
- Observaciones independientes por día de trading (sin continuidad temporal entre jornadas).

Bajo este enfoque, CatBoost actúa como un modelo supervisado de regresión, donde:
- Entrada (X): features agregadas o vectorizadas de la ventana histórica.
- Salida (y): target_return_90.

El modelo no asume estructura temporal explícita, sino que aprende patrones estadísticos que anticipan el comportamiento del precio a 90 minutos, lo cual es consistente con tu formulación actual del problema.

**Ventajas clave para este proyecto**

- Excelente desempeño en datasets tabulares con muchas features.
- Baja sensibilidad al escalado de variables.
- Buena robustez frente a ruido intradía.
- Entrenamiento eficiente y estable.
- Ideal como baseline fuerte frente a modelos más complejos (LSTM, Transformer, TFT).

## 0. Configuración del Entorno

### 0.1. Clonado de repositorio / Acceso a Drive

In [1]:
#Clonamos el repo
#LINK DE REPOSITORIO: https://github.com/GUNAPILLCO/neural_profit
#!git clone https://github.com/GUNAPILLCO/neural_profit.git

In [2]:
from google.colab import drive
drive.mount('/content/drive')
drive_path = "/content/drive/MyDrive/neural_profit"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### 0.2. Instalación de librerías

In [3]:
%pip uninstall -y catboost -q

# Alineamos el stack numérico y CatBoost en una sola transacción
%pip install --no-cache-dir -U \
  numpy==2.1.2 \
  scipy==1.13.1 \
  scikit-learn==1.5.2 \
  catboost==1.2.8 -q

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.2/99.2 MB 263.5 MB/s eta 0:00:00

In [4]:
import catboost
from catboost import CatBoostRegressor, Pool

### 0.3. Importación de librerías

In [5]:
# ==============================
# Librerías estándar de Python
# ==============================
import os
import sys
import re
import glob
import warnings
import requests
from datetime import datetime, timedelta
from functools import reduce

# ==============================
# Manejo y procesamiento de datos
# ==============================
import pandas as pd
import numpy as np
from tabulate import tabulate

# ==============================
# Visualización
# ==============================
import matplotlib.pyplot as plt

# ==============================
# Estadística
# ==============================
from scipy.stats import spearmanr

# ==============================
# Machine Learning y utilidades
# ==============================
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import sklearn, scipy
import sklearn, numpy, scipy #optuna
#from sklearn.ensemble import RandomForestRegressor

import joblib
#import optuna
from tqdm import tqdm

# ==============================
# Configuración general
# ==============================
warnings.filterwarnings("ignore")

import time

import xgboost as xgb
#from xgboost import XGBRegressor

import sys, platform, lightgbm as lgb
import numpy as np, pandas as pd
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
#from lightgbm import LGBMRegressor

In [ ]:
print("python:", sys.version)
print("Platform:", platform.platform())
print("numpy:", numpy.__version__)
print("scipy:", scipy.__version__)
print("sklearn:", sklearn.__version__)
#print("optuna:", optuna.__version__)
print("xgboost:", xgb.__version__)
print("lightgbm:", lgb.__version__)

# CatBoost usa la clase para exponer versión
print("catboost:", catboost.__version__)

## 1. Carga de datos

### 1.1. Carga de datasets `mnq_train`, `mnq_valid` y `mnq_test`

In [6]:
def load_data(data: str):

    data_path = f'{drive_path}/3_dataset_preparation/mnq_{data}.parquet'
    # Leer el archivo Parquet y cargarlo en un DataFrame
    df = pd.read_parquet(data_path)

    # Asegurar que el índice esté en formato datetime
    df.index = pd.to_datetime(df.index)

    # Crear una nueva columna 'date' con la fecha extraída del índice
    df['date'] = df.index.date

    # Reordenar columnas: 'date', 'time_str', y luego el resto
    cols = ['date'] + [col for col in df.columns if col not in ['date']]

    df = df[cols]

    return df

In [7]:
#mnq_train = load_data("train")
#mnq_valid = load_data("valid")
#mnq_test = load_data("test")

### 1.2. Información de datasets

In [8]:
def info_dataset(df, name: str):
  print(f"Información del dataset {name}:\n")

  # Contar valores únicos en la columna 'date'
  num_dias = df['date'].nunique()
  print(f"\tCantidad de días: {num_dias}")

  # Filtrar valores válidos
  validos_por_dia = df.dropna(subset=['close']).groupby('date').size()

  # Calcular el promedio
  promedio_por_fecha = validos_por_dia.mean()
  print(f"\tRegistros por día: {int(promedio_por_fecha)}")

  primer_hora = df.index[0].strftime('%H:%M')
  ultima_hora = df.index[-1].strftime('%H:%M')
  zona_horaria = df.index[0].tzinfo


  print(f"\tHora diaria de inicio {primer_hora}")
  print(f"\tHora diaria de final {ultima_hora}")
  print(f"\tZona horaria: {zona_horaria}\n")

  return num_dias, promedio_por_fecha

In [9]:
#info_dataset(mnq_train, 'mnq_train')
#info_dataset(mnq_valid, 'mnq_valid')
#info_dataset(mnq_test, 'mnq_test')

### 1.3. Carga de listado de features por ventana de tiempo

In [10]:
import json

# Ruta al archivo guardado
path = f'{drive_path}/2_feature_engineering/features_list.json'

with open(path, "r") as f:
    features_dict = json.load(f)

# Extraer las listas
#features_to_30 = features_dict["features_to_30"]
#features_to_60 = features_dict["features_to_60"]
#features_to_90 = features_dict["features_to_90"]

In [11]:
#print(f'Listado de features para 30min: {features_to_30}')
#print(f'Listado de features para 60min: {features_to_60}')
#print(f'Listado de features para 90min: {features_to_90}')

## **2. Carga de ventanas `X_train_*_scaled`, `X_valid_*_scaled`, `X_test_*_scaled`**

In [12]:
#Lista de K folds
k_folds = [1, 2, 3, 4, 5]

### 2.0. Funciones

#### Función para cargar ventanas

In [13]:
def load_windows_and_scaler(k: str, scaled=True):
    """
    Carga datasets (X, y) para train, valid y test junto con el scaler global.

    Parámetros
    ----------
    drive_path : str
        Ruta base donde se encuentran los archivos.
    scaled : bool, default=True
        Si True busca en la carpeta 'ventanas_x_y_scaled',
        si False en 'ventanas_x_y'.

    Retorna
    -------
    X_train, y_train, X_valid, y_valid, X_test, y_test, scaler
    """

    #Ruta de ventandas escaladas que usamos para transformer
    path_train  = f'{drive_path}/5_transformer_model/5_2_k_scaler/fold_{k}/X_train_sc_{k}.npz'
    path_valid  = f'{drive_path}/5_transformer_model/5_2_k_scaler/fold_{k}/X_valid_sc_{k}.npz'
    path_test   = f'{drive_path}/5_transformer_model/5_2_k_scaler/fold_{k}/X_test_sc_{k}.npz'

    #Ruta de escalador
    path_scaler = f"{drive_path}/5_transformer_model/5_2_k_scaler/global_scaler.pkl"

    # Cargar npz
    data_train = np.load(path_train)
    data_valid = np.load(path_valid)
    data_test  = np.load(path_test)

    # Extraer X, y
    X_train, y_train = data_train["X"], data_train["y"]
    print(f'\tX_train_sc_{k} e y_train_{k} extraídos correctamente')
    X_valid, y_valid = data_valid["X"], data_valid["y"]
    print(f'\tX_valid_sc_{k} e y_valid_{k} extraídos correctamente')
    X_test,  y_test  = data_test["X"],  data_test["y"]
    print(f'\tX_test_sc_{k} e y_test_{k} extraídos correctamente')

    # Cargar scaler
    scaler = joblib.load(path_scaler)

    return X_train, y_train, X_valid, y_valid, X_test, y_test, scaler

#### Función para revisar información de ventanas

In [14]:
def xy_info(k, X_train, y_train, X_valid, y_valid, X_test, y_test, silent=False):
    import numpy as np
    import psutil

    if not silent:
        print(f"Información de {k}:")
        print("----------------------------------------")

    # Memoria total
    total_ram_gb = psutil.virtual_memory().total / (1024 ** 3)

    def print_set_info(nombre, X, y):
        if silent:
            return  # No imprimir nada

        n_samples = X.shape[0]
        size_X_gb = X.nbytes / (1024 ** 3)
        size_y_gb = y.nbytes / (1024 ** 3)
        total_gb = size_X_gb + size_y_gb
        perc_ram = (total_gb / total_ram_gb) * 100
        y_flat = np.ravel(y)

        print(f"Set de {nombre}:")
        print(f"\t{n_samples} ventanas")
        print(f"\tTamaño X: {size_X_gb:.3f} GB")
        print(f"\tTamaño y: {size_y_gb:.6f} GB")
        print(f"\tTOTAL: {total_gb:.3f} GB → {perc_ram:.1f}% RAM\n")

    # Mostrar info solo si silent=False
    print_set_info("entrenamiento", X_train, y_train)
    print_set_info("validación",    X_valid, y_valid)
    print_set_info("testeo",        X_test,  y_test)

    # Pesos = cantidad de ventanas
    w_train = X_train.shape[0]
    w_valid = X_valid.shape[0]
    w_test  = X_test.shape[0]

    return w_train, w_valid, w_test

### 2.1. Carga de ventanas

In [15]:
#X_train_90_scaled, y_train_90, X_valid_90_scaled, y_valid_90, X_test_90_scaled, y_test_90, scaler_90 = load_windows_and_scaler(target = '90')

# Diccionarios para almacenar datos escalados por fold
X_train_sc = {}
y_train_sc = {}
X_valid_sc = {}
y_valid_sc = {}
X_test_sc  = {}
y_test_sc  = {}
scalers    = {}

for k in k_folds:
    print(f'Fold {k}:')

    X_train, y_train, X_valid, y_valid, X_test, y_test, scaler = load_windows_and_scaler(k)

    # Guardar todo en diccionarios
    X_train_sc[k] = X_train
    y_train_sc[k] = y_train

    X_valid_sc[k] = X_valid
    y_valid_sc[k] = y_valid

    X_test_sc[k]  = X_test
    y_test_sc[k]  = y_test

    scalers[k] = scaler

    print(f"  - Datos escalados cargados y almacenados en diccionarios.")
    print("-" * 40)

Fold 1:
	X_train_sc_1 e y_train_1 extraídos correctamente
	X_valid_sc_1 e y_valid_1 extraídos correctamente
	X_test_sc_1 e y_test_1 extraídos correctamente
  - Datos escalados cargados y almacenados en diccionarios.
----------------------------------------
Fold 2:
	X_train_sc_2 e y_train_2 extraídos correctamente
	X_valid_sc_2 e y_valid_2 extraídos correctamente
	X_test_sc_2 e y_test_2 extraídos correctamente
  - Datos escalados cargados y almacenados en diccionarios.
----------------------------------------
Fold 3:
	X_train_sc_3 e y_train_3 extraídos correctamente
	X_valid_sc_3 e y_valid_3 extraídos correctamente
	X_test_sc_3 e y_test_3 extraídos correctamente
  - Datos escalados cargados y almacenados en diccionarios.
----------------------------------------
Fold 4:
	X_train_sc_4 e y_train_4 extraídos correctamente
	X_valid_sc_4 e y_valid_4 extraídos correctamente
	X_test_sc_4 e y_test_4 extraídos correctamente
  - Datos escalados cargados y almacenados en diccionarios.
----------------------------------------
Fold 5:
	X_train_sc_5 e y_train_5 extraídos correctamente
	X_valid_sc_5 e y_valid_5 extraídos correctamente
	X_test_sc_5 e y_test_5 extraídos correctamente
  - Datos escalados cargados y almacenados en diccionarios.
----------------------------------------

In [16]:
pesos_folds = {}

for k in k_folds:
    w_train, w_valid, w_test = xy_info(
        k,
        X_train_sc[k],
        y_train_sc[k],
        X_valid_sc[k],
        y_valid_sc[k],
        X_test_sc[k],
        y_test_sc[k],
        silent=True   # evita imprimir
    )

    pesos_folds[k] = {
        "w_train": w_train,
        "w_valid": w_valid,
        "w_test":  w_test,
    }

## **3. Dataset de Métricas**

Dado que cada entrenamiento demanda un tiempo considerable, antes de proceder verificaremos si ya existe un resultado previo de este modelo consultando el dataset de métricas.

### 3.1. Función para cargar métricas o generar dataset

In [17]:
def load_metrics(subcarpeta: str, data: str):
    data_path = f'{drive_path}/6_catboost_model/{subcarpeta}/{data}.parquet'
    # Leer el archivo Parquet y cargarlo en un DataFrame
    df = pd.read_parquet(data_path)
    return df

In [18]:
def metrics_verify(subcarpeta: str, data: str) -> bool:
    data_path = f'{drive_path}/v_model/{subcarpeta}/{data}.parquet'
    return os.path.exists(data_path)

In [19]:
def load_or_create_metrics (subcarpeta: str, data:str):
  if metrics_verify(subcarpeta, data):
      print(f"Las métricas existen y son almacenadas en {data[2:len(data)]}")
      model_metrics = load_metrics(subcarpeta, data)
      metrics = True
  else:
      print(f"Las métricas no existen. Se crea el dataset {data[2:len(data)]} para almacenar las métricas")
      #Creamos la tabla para almacenar las métricas
      model_metrics = pd.DataFrame(columns=["RMSE", "MAE", "R2", "SMAPE", "DirAcc"])
      metrics = False

  return model_metrics, metrics

In [20]:
baseline_folds_metrics, flag_baseline_folds_metrics = load_or_create_metrics("6_1_baseline_model", "0_baseline_folds_metrics")
baseline_metrics, flag_baseline_metrics = load_or_create_metrics("6_1_baseline_model", "1_baseline_metrics")

Las métricas no existen. Se crea el dataset baseline_folds_metrics para almacenar las métricas
Las métricas no existen. Se crea el dataset baseline_metrics para almacenar las métricas

### 3.2. Función para guardar métricas

In [21]:
def save_metrics (metrics,  subcarpeta: str, metrics_name: str):
  metrics_path = f"{drive_path}/6_catboost_model/{subcarpeta}/{metrics_name}.parquet"
  metrics.to_parquet(metrics_path, index = True)
  print(f"Métricas guardadas en {metrics_path}")

### 3.3. Función para calcular las métricas

In [22]:
def evaluate_model(model, X, y_true, y_pred=None, eps=1e-8):
    """
    Evalúa RMSE, MAE, R2, SMAPE y DirAcc.
    - Si y_pred es None, predice con el modelo usando X.
    - Evita mean_squared_error(squared=...) para máxima compatibilidad.
    """
    if y_pred is None:
        y_pred = model.predict(X)

    # Asegurar 1D
    y_true = np.ravel(y_true)
    y_pred = np.ravel(y_pred)

    # RMSE sin sklearn
    rmse = float(np.sqrt(np.mean((y_true - y_pred) ** 2)))
    mae = float(mean_absolute_error(y_true, y_pred))
    r2  = float(r2_score(y_true, y_pred))

    # SMAPE
    smape_val = 100.0 * np.mean(
        (np.abs(y_true - y_pred) / ((np.abs(y_true) + np.abs(y_pred)) / 2.0 + eps))
    )

    # Directional Accuracy
    directional_acc = float(np.mean(np.sign(y_true) == np.sign(y_pred)))

    return {
        "RMSE": rmse,
        "MAE": mae,
        "R2": r2,
        "SMAPE": float(smape_val),
        "DirAcc": directional_acc
    }

In [23]:
def print_metrics(metrics, target:str):
  print(f"Métricas de {target}:\n")
  for k, v in metrics.items():
      print(f"\t{k:>5}:\t {float(v):.6f}")

## **4. Definición de modelo**

### **4.1. Función de entrenamiento para modelo**

In [24]:
from catboost import CatBoostRegressor, Pool

def train_model_catboost(
    best_params,
    X_train, y_train,
    X_valid, y_valid,
    *,
    cat_features=None,
    use_gpu=False,
    iterations=5000,
    od_wait=200,
    verbose_every=200
):
    """
    Entrena un modelo CatBoostRegressor usando early stopping.

    NOTA IMPORTANTE:
    - NO se usan pesos de entrenamiento.
    - Los pesos por fold se utilizarán únicamente para ponderar métricas
      en la etapa de evaluación final.
    """

    # ------------------------------------------------------------------
    # 1. Copia de hiperparámetros
    # ------------------------------------------------------------------
    # Se copia el diccionario para no modificar el original
    params = dict(best_params or {})

    # ------------------------------------------------------------------
    # 2. Defaults de CatBoost (si no vienen definidos)
    # ------------------------------------------------------------------
    params.setdefault("loss_function", "RMSE")   # función de pérdida
    params.setdefault("eval_metric", "RMSE")     # métrica de validación
    params.setdefault("random_seed", 42)         # reproducibilidad
    params.setdefault("use_best_model", True)    # conserva la mejor iteración
    params.setdefault("od_type", "Iter")         # early stopping por iteraciones
    params.setdefault("od_wait", od_wait)        # paciencia del early stopping
    params.setdefault("verbose", verbose_every)  # frecuencia de logs
    params.setdefault("thread_count", -1)        # usa todos los cores
    params.setdefault("iterations", iterations) # máximo de árboles
    params.setdefault("allow_writing_files", False)  # evita archivos temporales

    # ------------------------------------------------------------------
    # 3. Configuración opcional de GPU
    # ------------------------------------------------------------------
    if use_gpu:
        params["task_type"] = "GPU"
        # params["devices"] = "0"  # opcional, si querés fijar GPU

    # ------------------------------------------------------------------
    # 4. Creación de Pools
    # ------------------------------------------------------------------
    # Pool es la estructura interna eficiente de CatBoost
    # Aquí NO se pasan pesos
    train_pool = Pool(
        X_train,
        y_train,
        cat_features=cat_features
    )

    valid_pool = Pool(
        X_valid,
        y_valid,
        cat_features=cat_features
    )

    # ------------------------------------------------------------------
    # 5. Entrenamiento del modelo
    # ------------------------------------------------------------------
    model = CatBoostRegressor(**params)
    model.fit(
        train_pool,
        eval_set=valid_pool
    )

    # ------------------------------------------------------------------
    # 6. Predicción sobre validación
    # ------------------------------------------------------------------
    # Con use_best_model=True, predict() usa automáticamente
    # la mejor iteración encontrada en validación
    preds_valid = model.predict(valid_pool)

    # ------------------------------------------------------------------
    # 7. Salida
    # ------------------------------------------------------------------
    return model, preds_valid

### **4.2. Hiperparámetros baseline para modelo**

In [25]:
# ------------------------------------------------------------------
# Parámetros baseline para CatBoost (regresión)
# Horizonte objetivo: retorno a 90 minutos
# Configuración pensada para entrenamiento en GPU
# ------------------------------------------------------------------

catboost_baseline_params = {
    # --------------------------------------------------------------
    # Función de pérdida y métrica de evaluación
    # --------------------------------------------------------------
    "loss_function": "RMSE",   # Optimiza el error cuadrático medio
    "eval_metric": "RMSE",     # Métrica usada para early stopping

    # --------------------------------------------------------------
    # Parámetros de boosting
    # --------------------------------------------------------------
    "learning_rate": 0.02,     # Tasa de aprendizaje baja para mayor estabilidad
    "depth": 8,                # Profundidad de los árboles (capacidad del modelo)
    "l2_leaf_reg": 3.0,        # Regularización L2 para reducir overfitting

    # --------------------------------------------------------------
    # Estocasticidad (compatible con GPU)
    # --------------------------------------------------------------
    # "rsm": 0.8,               # Submuestreo de features (NO compatible con GPU)
    # "subsample": 0.8,         # Bootstrap clásico (NO recomendado en GPU)
    "bagging_temperature": 1.0,  # Bayesian bootstrap (sí compatible con GPU)
    "random_strength": 1.0,       # Ruido en la selección de splits

    # --------------------------------------------------------------
    # Reproducibilidad
    # --------------------------------------------------------------
    "random_seed": 42,         # Semilla fija para resultados reproducibles

    # --------------------------------------------------------------
    # Early stopping
    # --------------------------------------------------------------
    "use_best_model": True,    # Conserva el mejor modelo según validación
    "od_type": "Iter",         # Early stopping basado en iteraciones
    "od_wait": 200,            # Paciencia del early stopping

    # --------------------------------------------------------------
    # Configuración de hardware
    # --------------------------------------------------------------
    "task_type": "GPU",        # Entrenamiento en GPU

    # --------------------------------------------------------------
    # Logging
    # --------------------------------------------------------------
    "verbose": 200,            # Frecuencia de impresión del progreso
}

### **4.3. Función conjunta**

In [26]:
def run_catboost_experiment(
    metrics_flag: bool,
    model_key: str,
    X_train_scaled,
    y_train,
    X_valid_scaled,
    y_valid,
    catboost_params: dict,
    catboost_metrics_df: pd.DataFrame | None = None,
    *,
    # extras específicos de CatBoost (opcionales)
    cat_features=None,          # índices o nombres de columnas categóricas
    use_gpu: bool = False,
    iterations: int = 5000,
    od_wait: int = 200,
    verbose_every: int = 200,
):
    """
    Ejecuta un experimento CatBoost SIN subsampleo (usa todo train/valid).

    Parámetros
    ----------
    metrics_flag : bool
        Si True, no entrena y busca métricas previas en catboost_metrics_df[model_key].
    model_key : str
        Nombre/índice del modelo en la tabla de métricas (ej: 'CAT_90_fold_1').
    X_train_scaled, y_train : arrays
        Dataset de entrenamiento (ya escalado si corresponde).
    X_valid_scaled, y_valid : arrays
        Dataset de validación (ya escalado si corresponde).
    catboost_params : dict
        Hiperparámetros nativos de CatBoost (depth, learning_rate, l2_leaf_reg, etc.).
    catboost_metrics_df : pd.DataFrame | None
        DataFrame de métricas para leer/escribir (index por model_key). Opcional.

    Retorna
    -------
    dict
        Diccionario con métricas {"RMSE","MAE","R2","SMAPE","DirAcc"}.
    """

    # ------------------------------------------------------------
    # 1) Si ya hay métricas guardadas y metrics_flag=True, devolverlas
    # ------------------------------------------------------------
    if (
        metrics_flag is True
        and catboost_metrics_df is not None
        and model_key in catboost_metrics_df.index
    ):
        print("El modelo fue entrenado anteriormente y las métricas ya fueron calculadas\n")
        metrics_dict = catboost_metrics_df.loc[model_key].to_dict()
        print_metrics(metrics_dict, model_key)
        return metrics_dict

    # ------------------------------------------------------------
    # 2) Entrenar usando todo el train/valid (sin subsampleo)
    # ------------------------------------------------------------
    print(f"Entrenando modelo {model_key} (sin resample)...")

    model, y_pred_valid = train_model_catboost(
        best_params=catboost_params,
        X_train=X_train_scaled, y_train=y_train,
        X_valid=X_valid_scaled, y_valid=y_valid,
        cat_features=cat_features,
        use_gpu=use_gpu,
        iterations=iterations,
        od_wait=od_wait,
        verbose_every=verbose_every
    )

    # ------------------------------------------------------------
    # 3) Evaluar en validación
    # ------------------------------------------------------------
    metrics_dict = evaluate_model(model, X_valid_scaled, y_valid, y_pred=y_pred_valid)

    # ------------------------------------------------------------
    # 4) Mostrar métricas
    # ------------------------------------------------------------
    print_metrics(metrics_dict, model_key)

    # ------------------------------------------------------------
    # 5) Guardar métricas si se pasó el DataFrame
    # ------------------------------------------------------------
    if catboost_metrics_df is not None:
        catboost_metrics_df.loc[model_key] = metrics_dict

    return metrics_dict

## **5. Entrenamiento**

In [27]:
if flag_baseline_folds_metrics:
      print("flag_baseline_folds_metrics=True → se omite el entrenamiento de todos los folds.")
else:
      print("flag_baseline_metrics=False → se inicia entrenamiento por folds.")

      for k in k_folds:
          #Definir una clave de modelo por fold (para registro de métricas)
          print(f"Fold {k}:")
          model_key = f"CAT_baseline_fold_{k}"

          # Si ya existe en la tabla de métricas, omitimos SOLO ese fold
          if ("baseline_folds_metrics" in globals()
              and baseline_folds_metrics is not None
              and model_key in baseline_folds_metrics.index):
              print(f"Omitimos este entrenamiento: {model_key} ya existe en baseline_folds_metrics")
              continue

          print(f"\n=== Entrenando modelo: {model_key} ===")
          metrics_k = run_catboost_experiment(
              metrics_flag=flag_baseline_folds_metrics,
              model_key=model_key,
              X_train_scaled=X_train_sc[k],
              y_train=y_train_sc[k],
              X_valid_scaled=X_valid_sc[k],
              y_valid=y_valid_sc[k],
              catboost_params=catboost_baseline_params,
              catboost_metrics_df=baseline_folds_metrics,
              use_gpu=True
              )

flag_baseline_metrics=False → se inicia entrenamiento por folds.
Fold 1:

=== Entrenando modelo: CAT_baseline_fold_1 ===
Entrenando modelo CAT_baseline_fold_1 (sin resample)...
0:	learn: 0.0050748	test: 0.0058573	best: 0.0058573 (0)	total: 96.4ms	remaining: 8m 1s
200:	learn: 0.0032823	test: 0.0043493	best: 0.0043493 (200)	total: 8.39s	remaining: 3m 20s
400:	learn: 0.0029473	test: 0.0042529	best: 0.0042528 (396)	total: 20.2s	remaining: 3m 51s
600:	learn: 0.0027462	test: 0.0042200	best: 0.0042200 (600)	total: 28.3s	remaining: 3m 27s
800:	learn: 0.0025969	test: 0.0042019	best: 0.0042019 (800)	total: 36.3s	remaining: 3m 10s
1000:	learn: 0.0024727	test: 0.0041825	best: 0.0041824 (999)	total: 45.1s	remaining: 3m
1200:	learn: 0.0023672	test: 0.0041703	best: 0.0041699 (1197)	total: 54.4s	remaining: 2m 52s
1400:	learn: 0.0022776	test: 0.0041599	best: 0.0041598 (1398)	total: 1m 3s	remaining: 2m 43s
1600:	learn: 0.0021950	test: 0.0041512	best: 0.0041512 (1599)	total: 1m 14s	remaining: 2m 37s
1800:	learn: 0.0021239	test: 0.0041443	best: 0.0041443 (1800)	total: 1m 22s	remaining: 2m 26s
2000:	learn: 0.0020563	test: 0.0041369	best: 0.0041368 (1994)	total: 1m 30s	remaining: 2m 15s
2200:	learn: 0.0019943	test: 0.0041301	best: 0.0041301 (2200)	total: 1m 40s	remaining: 2m 7s
2400:	learn: 0.0019371	test: 0.0041263	best: 0.0041263 (2400)	total: 1m 48s	remaining: 1m 57s
2600:	learn: 0.0018821	test: 0.0041226	best: 0.0041225 (2597)	total: 1m 58s	remaining: 1m 49s
2800:	learn: 0.0018348	test: 0.0041178	best: 0.0041178 (2796)	total: 2m 7s	remaining: 1m 39s
3000:	learn: 0.0017879	test: 0.0041156	best: 0.0041154 (2967)	total: 2m 15s	remaining: 1m 30s
3200:	learn: 0.0017436	test: 0.0041132	best: 0.0041130 (3130)	total: 2m 26s	remaining: 1m 22s
3400:	learn: 0.0017003	test: 0.0041125	best: 0.0041117 (3339)	total: 2m 37s	remaining: 1m 13s
3600:	learn: 0.0016600	test: 0.0041092	best: 0.0041091 (3592)	total: 2m 47s	remaining: 1m 5s
3800:	learn: 0.0016202	test: 0.0041062	best: 0.0041062 (3783)	total: 2m 57s	remaining: 56s
4000:	learn: 0.0015848	test: 0.0041043	best: 0.0041042 (3997)	total: 3m 5s	remaining: 46.4s
4200:	learn: 0.0015480	test: 0.0041024	best: 0.0041023 (4198)	total: 3m 14s	remaining: 37.1s
4400:	learn: 0.0015137	test: 0.0041004	best: 0.0041001 (4370)	total: 3m 22s	remaining: 27.6s
4600:	learn: 0.0014815	test: 0.0040998	best: 0.0040997 (4598)	total: 3m 31s	remaining: 18.4s
4800:	learn: 0.0014507	test: 0.0040991	best: 0.0040990 (4798)	total: 3m 40s	remaining: 9.15s
4999:	learn: 0.0014220	test: 0.0040969	best: 0.0040969 (4997)	total: 3m 48s	remaining: 0us
bestTest = 0.004096912105
bestIteration = 4997
Shrink model to first 4998 iterations.
Métricas de CAT_baseline_fold_1:

	 RMSE:	 0.004097
	  MAE:	 0.002874
	   R2:	 0.515733
	SMAPE:	 92.241222
	DirAcc:	 0.800345
Fold 2:

=== Entrenando modelo: CAT_baseline_fold_2 ===
Entrenando modelo CAT_baseline_fold_2 (sin resample)...
0:	learn: 0.0052118	test: 0.0042424	best: 0.0042424 (0)	total: 110ms	remaining: 9m 9s
200:	learn: 0.0034699	test: 0.0029399	best: 0.0029399 (200)	total: 8.54s	remaining: 3m 23s
400:	learn: 0.0031592	test: 0.0028656	best: 0.0028656 (400)	total: 18.1s	remaining: 3m 27s
600:	learn: 0.0029772	test: 0.0028345	best: 0.0028345 (600)	total: 26.9s	remaining: 3m 16s
800:	learn: 0.0028311	test: 0.0028095	best: 0.0028095 (800)	total: 35.6s	remaining: 3m 6s
1000:	learn: 0.0027090	test: 0.0027855	best: 0.0027855 (1000)	total: 45s	remaining: 2m 59s
1200:	learn: 0.0026075	test: 0.0027717	best: 0.0027717 (1200)	total: 54.1s	remaining: 2m 51s
1400:	learn: 0.0025191	test: 0.0027591	best: 0.0027591 (1400)	total: 1m 2s	remaining: 2m 41s
1600:	learn: 0.0024406	test: 0.0027515	best: 0.0027515 (1600)	total: 1m 12s	remaining: 2m 33s
1800:	learn: 0.0023660	test: 0.0027420	best: 0.0027420 (1794)	total: 1m 20s	remaining: 2m 23s
2000:	learn: 0.0022979	test: 0.0027336	best: 0.0027336 (2000)	total: 1m 29s	remaining: 2m 14s
2200:	learn: 0.0022365	test: 0.0027277	best: 0.0027277 (2200)	total: 1m 39s	remaining: 2m 6s
2400:	learn: 0.0021778	test: 0.0027233	best: 0.0027230 (2387)	total: 1m 48s	remaining: 1m 57s
2600:	learn: 0.0021224	test: 0.0027191	best: 0.0027191 (2600)	total: 1m 57s	remaining: 1m 48s
2800:	learn: 0.0020718	test: 0.0027140	best: 0.0027140 (2800)	total: 2m 6s	remaining: 1m 39s
3000:	learn: 0.0020230	test: 0.0027101	best: 0.0027101 (3000)	total: 2m 15s	remaining: 1m 30s
3200:	learn: 0.0019782	test: 0.0027076	best: 0.0027075 (3191)	total: 2m 24s	remaining: 1m 21s
3400:	learn: 0.0019352	test: 0.0027052	best: 0.0027052 (3399)	total: 2m 33s	remaining: 1m 12s
3600:	learn: 0.0018934	test: 0.0027032	best: 0.0027032 (3600)	total: 2m 42s	remaining: 1m 3s
3800:	learn: 0.0018539	test: 0.0027014	best: 0.0027014 (3792)	total: 2m 51s	remaining: 54.2s
4000:	learn: 0.0018154	test: 0.0027007	best: 0.0027006 (3997)	total: 3m 1s	remaining: 45.3s
4200:	learn: 0.0017806	test: 0.0026986	best: 0.0026985 (4196)	total: 3m 10s	remaining: 36.3s
4400:	learn: 0.0017457	test: 0.0026980	best: 0.0026978 (4341)	total: 3m 19s	remaining: 27.2s
4600:	learn: 0.0017127	test: 0.0026958	best: 0.0026957 (4599)	total: 3m 31s	remaining: 18.3s
4800:	learn: 0.0016825	test: 0.0026962	best: 0.0026957 (4656)	total: 3m 40s	remaining: 9.15s
4999:	learn: 0.0016524	test: 0.0026946	best: 0.0026944 (4987)	total: 3m 49s	remaining: 0us
bestTest = 0.002694438233
bestIteration = 4987
Shrink model to first 4988 iterations.
Métricas de CAT_baseline_fold_2:

	 RMSE:	 0.002694
	  MAE:	 0.001915
	   R2:	 0.602590
	SMAPE:	 86.919758
	DirAcc:	 0.816331
Fold 3:

=== Entrenando modelo: CAT_baseline_fold_3 ===
Entrenando modelo CAT_baseline_fold_3 (sin resample)...
0:	learn: 0.0050846	test: 0.0034417	best: 0.0034417 (0)	total: 85.2ms	remaining: 7m 6s
200:	learn: 0.0034153	test: 0.0023373	best: 0.0023373 (200)	total: 8.82s	remaining: 3m 30s
400:	learn: 0.0031267	test: 0.0022752	best: 0.0022752 (400)	total: 18.1s	remaining: 3m 27s
600:	learn: 0.0029522	test: 0.0022350	best: 0.0022350 (600)	total: 27.6s	remaining: 3m 21s
800:	learn: 0.0028174	test: 0.0022004	best: 0.0022004 (800)	total: 38.8s	remaining: 3m 23s
1000:	learn: 0.0027066	test: 0.0021757	best: 0.0021757 (1000)	total: 47.5s	remaining: 3m 9s
1200:	learn: 0.0026117	test: 0.0021549	best: 0.0021549 (1200)	total: 1m	remaining: 3m 9s
1400:	learn: 0.0025269	test: 0.0021407	best: 0.0021407 (1400)	total: 1m 9s	remaining: 2m 59s
1600:	learn: 0.0024519	test: 0.0021300	best: 0.0021300 (1600)	total: 1m 19s	remaining: 2m 49s
1800:	learn: 0.0023848	test: 0.0021192	best: 0.0021190 (1798)	total: 1m 28s	remaining: 2m 37s
2000:	learn: 0.0023229	test: 0.0021108	best: 0.0021108 (1998)	total: 1m 38s	remaining: 2m 27s
2200:	learn: 0.0022622	test: 0.0021047	best: 0.0021047 (2197)	total: 1m 48s	remaining: 2m 17s
2400:	learn: 0.0022068	test: 0.0020981	best: 0.0020978 (2395)	total: 1m 57s	remaining: 2m 7s
2600:	learn: 0.0021571	test: 0.0020960	best: 0.0020959 (2582)	total: 2m 6s	remaining: 1m 57s
2800:	learn: 0.0021091	test: 0.0020926	best: 0.0020923 (2782)	total: 2m 16s	remaining: 1m 47s
3000:	learn: 0.0020659	test: 0.0020884	best: 0.0020881 (2997)	total: 2m 26s	remaining: 1m 37s
3200:	learn: 0.0020257	test: 0.0020862	best: 0.0020862 (3200)	total: 2m 35s	remaining: 1m 27s
3400:	learn: 0.0019873	test: 0.0020835	best: 0.0020834 (3397)	total: 2m 45s	remaining: 1m 17s
3600:	learn: 0.0019495	test: 0.0020820	best: 0.0020818 (3594)	total: 2m 55s	remaining: 1m 8s
3800:	learn: 0.0019136	test: 0.0020798	best: 0.0020798 (3798)	total: 3m 4s	remaining: 58.1s
4000:	learn: 0.0018782	test: 0.0020787	best: 0.0020785 (3924)	total: 3m 13s	remaining: 48.4s
4200:	learn: 0.0018442	test: 0.0020769	best: 0.0020769 (4200)	total: 3m 23s	remaining: 38.8s
4400:	learn: 0.0018122	test: 0.0020755	best: 0.0020754 (4378)	total: 3m 33s	remaining: 29s
4600:	learn: 0.0017815	test: 0.0020738	best: 0.0020738 (4600)	total: 3m 42s	remaining: 19.3s
4800:	learn: 0.0017511	test: 0.0020730	best: 0.0020728 (4782)	total: 3m 52s	remaining: 9.63s
4999:	learn: 0.0017229	test: 0.0020724	best: 0.0020722 (4935)	total: 4m 2s	remaining: 0us
bestTest = 0.002072212184
bestIteration = 4935
Shrink model to first 4936 iterations.
Métricas de CAT_baseline_fold_3:

	 RMSE:	 0.002072
	  MAE:	 0.001544
	   R2:	 0.644495
	SMAPE:	 88.151569
	DirAcc:	 0.812997
Fold 4:

=== Entrenando modelo: CAT_baseline_fold_4 ===
Entrenando modelo CAT_baseline_fold_4 (sin resample)...
0:	learn: 0.0049106	test: 0.0033125	best: 0.0033125 (0)	total: 89ms	remaining: 7m 24s
200:	learn: 0.0033070	test: 0.0023574	best: 0.0023574 (200)	total: 9.99s	remaining: 3m 58s
400:	learn: 0.0030382	test: 0.0022982	best: 0.0022982 (400)	total: 20.1s	remaining: 3m 50s
600:	learn: 0.0028767	test: 0.0022470	best: 0.0022470 (600)	total: 29.1s	remaining: 3m 32s
800:	learn: 0.0027511	test: 0.0022093	best: 0.0022093 (800)	total: 39.2s	remaining: 3m 25s
1000:	learn: 0.0026479	test: 0.0021782	best: 0.0021782 (1000)	total: 49.4s	remaining: 3m 17s
1200:	learn: 0.0025592	test: 0.0021551	best: 0.0021551 (1200)	total: 59.5s	remaining: 3m 8s
1400:	learn: 0.0024812	test: 0.0021369	best: 0.0021369 (1400)	total: 1m 8s	remaining: 2m 56s
1600:	learn: 0.0024125	test: 0.0021242	best: 0.0021242 (1600)	total: 1m 18s	remaining: 2m 47s
1800:	learn: 0.0023504	test: 0.0021134	best: 0.0021134 (1800)	total: 1m 29s	remaining: 2m 38s
2000:	learn: 0.0022914	test: 0.0021022	best: 0.0021021 (1999)	total: 1m 39s	remaining: 2m 28s
2200:	learn: 0.0022371	test: 0.0020937	best: 0.0020937 (2200)	total: 1m 48s	remaining: 2m 17s
2400:	learn: 0.0021873	test: 0.0020871	best: 0.0020871 (2400)	total: 1m 58s	remaining: 2m 8s
2600:	learn: 0.0021414	test: 0.0020812	best: 0.0020812 (2600)	total: 2m 8s	remaining: 1m 58s
2800:	learn: 0.0020979	test: 0.0020756	best: 0.0020755 (2797)	total: 2m 18s	remaining: 1m 48s
3000:	learn: 0.0020561	test: 0.0020728	best: 0.0020725 (2999)	total: 2m 28s	remaining: 1m 38s
3200:	learn: 0.0020160	test: 0.0020701	best: 0.0020699 (3198)	total: 2m 38s	remaining: 1m 29s
3400:	learn: 0.0019803	test: 0.0020669	best: 0.0020668 (3392)	total: 2m 48s	remaining: 1m 19s
3600:	learn: 0.0019450	test: 0.0020638	best: 0.0020638 (3594)	total: 2m 58s	remaining: 1m 9s
3800:	learn: 0.0019116	test: 0.0020622	best: 0.0020621 (3734)	total: 3m 8s	remaining: 59.4s
4000:	learn: 0.0018804	test: 0.0020593	best: 0.0020593 (4000)	total: 3m 18s	remaining: 49.6s
4200:	learn: 0.0018503	test: 0.0020581	best: 0.0020581 (4197)	total: 3m 28s	remaining: 39.7s
4400:	learn: 0.0018216	test: 0.0020565	best: 0.0020565 (4399)	total: 3m 38s	remaining: 29.7s
4600:	learn: 0.0017932	test: 0.0020555	best: 0.0020552 (4531)	total: 3m 48s	remaining: 19.8s
4800:	learn: 0.0017666	test: 0.0020535	best: 0.0020535 (4798)	total: 3m 58s	remaining: 9.89s
4999:	learn: 0.0017411	test: 0.0020519	best: 0.0020519 (4999)	total: 4m 8s	remaining: 0us
bestTest = 0.002051927544
bestIteration = 4999
Métricas de CAT_baseline_fold_4:

	 RMSE:	 0.002052
	  MAE:	 0.001408
	   R2:	 0.623467
	SMAPE:	 90.252562
	DirAcc:	 0.797895
Fold 5:

=== Entrenando modelo: CAT_baseline_fold_5 ===
Entrenando modelo CAT_baseline_fold_5 (sin resample)...
0:	learn: 0.0047603	test: 0.0033587	best: 0.0033587 (0)	total: 96.9ms	remaining: 8m 4s
200:	learn: 0.0032233	test: 0.0022211	best: 0.0022211 (200)	total: 10.3s	remaining: 4m 5s
400:	learn: 0.0029651	test: 0.0021374	best: 0.0021374 (400)	total: 20.7s	remaining: 3m 56s
600:	learn: 0.0028094	test: 0.0020904	best: 0.0020904 (600)	total: 30.9s	remaining: 3m 45s
800:	learn: 0.0026917	test: 0.0020529	best: 0.0020524 (797)	total: 40.3s	remaining: 3m 31s
1000:	learn: 0.0025952	test: 0.0020282	best: 0.0020282 (999)	total: 50.7s	remaining: 3m 22s
1200:	learn: 0.0025108	test: 0.0020125	best: 0.0020119 (1187)	total: 1m 1s	remaining: 3m 13s
1400:	learn: 0.0024369	test: 0.0019963	best: 0.0019963 (1400)	total: 1m 11s	remaining: 3m 4s
1600:	learn: 0.0023711	test: 0.0019843	best: 0.0019843 (1599)	total: 1m 21s	remaining: 2m 53s
1800:	learn: 0.0023113	test: 0.0019726	best: 0.0019726 (1800)	total: 1m 32s	remaining: 2m 43s
2000:	learn: 0.0022574	test: 0.0019664	best: 0.0019663 (1968)	total: 1m 42s	remaining: 2m 33s
2200:	learn: 0.0022090	test: 0.0019591	best: 0.0019591 (2200)	total: 1m 53s	remaining: 2m 23s
2400:	learn: 0.0021636	test: 0.0019566	best: 0.0019566 (2398)	total: 2m 2s	remaining: 2m 13s
2600:	learn: 0.0021212	test: 0.0019520	best: 0.0019518 (2586)	total: 2m 13s	remaining: 2m 2s
2800:	learn: 0.0020788	test: 0.0019492	best: 0.0019492 (2798)	total: 2m 23s	remaining: 1m 52s
3000:	learn: 0.0020389	test: 0.0019489	best: 0.0019469 (2924)	total: 2m 34s	remaining: 1m 42s
3200:	learn: 0.0020015	test: 0.0019443	best: 0.0019443 (3200)	total: 2m 45s	remaining: 1m 32s
3400:	learn: 0.0019682	test: 0.0019423	best: 0.0019422 (3398)	total: 2m 54s	remaining: 1m 22s
3600:	learn: 0.0019352	test: 0.0019417	best: 0.0019417 (3600)	total: 3m 5s	remaining: 1m 12s
3800:	learn: 0.0019031	test: 0.0019396	best: 0.0019393 (3785)	total: 3m 15s	remaining: 1m 1s
4000:	learn: 0.0018730	test: 0.0019373	best: 0.0019372 (3999)	total: 3m 26s	remaining: 51.6s
4200:	learn: 0.0018452	test: 0.0019353	best: 0.0019351 (4186)	total: 3m 36s	remaining: 41.2s
4400:	learn: 0.0018169	test: 0.0019338	best: 0.0019338 (4400)	total: 3m 46s	remaining: 30.9s
4600:	learn: 0.0017910	test: 0.0019320	best: 0.0019320 (4600)	total: 3m 57s	remaining: 20.6s
4800:	learn: 0.0017651	test: 0.0019322	best: 0.0019312 (4712)	total: 4m 7s	remaining: 10.3s
bestTest = 0.001931236992
bestIteration = 4712
Shrink model to first 4713 iterations.
Métricas de CAT_baseline_fold_5:

	 RMSE:	 0.001931
	  MAE:	 0.001432
	   R2:	 0.675379
	SMAPE:	 87.672135
	DirAcc:	 0.811712

## **6. Métricas**

In [28]:
if flag_baseline_folds_metrics:
    print("flag_baseline_folds_metrics=True → ya existen métricas del entrenamiento.")
else:
    print("flag_baseline_folds_metrics=False → se inicia entrenamiento por folds.")
    cols_base = ["RMSE", "MAE", "R2", "SMAPE", "DirAcc"]
    # columnas que efectivamente existen en el DataFrame
    cols_to_drop = [c for c in cols_base if c in baseline_folds_metrics.columns]
    # eliminar solo si hay columnas para eliminar
    if cols_to_drop:
        baseline_folds_metrics = baseline_folds_metrics.drop(columns=cols_to_drop)

flag_baseline_folds_metrics=False → se inicia entrenamiento por folds.

In [29]:
baseline_folds_metrics

Empty DataFrame
Columns: []
Index: [CAT_baseline_fold_1, CAT_baseline_fold_2, CAT_baseline_fold_3, CAT_baseline_fold_4, CAT_baseline_fold_5]

In [33]:
if flag_baseline_folds_metrics == False:
  save_metrics(baseline_folds_metrics, "/","0_baseline_folds_metrics")
else:
  print("Ya existen métricas del entrenamiento y están guardadas en disco")

Métricas guardadas en /content/drive/MyDrive/neural_profit/6_catboost_model///0_baseline_folds_metrics.parquet

In [34]:
def weighted_avg_metrics_from_df(df, w_train, w_valid, w_test):
    """
    Calcula el promedio ponderado de métricas a partir de un DataFrame
    con columnas del tipo train_RMSE, valid_RMSE, test_RMSE, etc.

    df : DataFrame con un fold por fila
    w_train, w_valid, w_test : pesos (cantidad de muestras por conjunto)
    """

    # Métricas base
    metricas = ["RMSE", "MAE", "R2", "SMAPE", "DirAcc"]

    resultados = {}

    for m in metricas:
        col_train = f"train_{m}"
        col_valid = f"valid_{m}"
        col_test  = f"test_{m}"

        # Promedio ponderado por fold, luego promedio entre folds
        valores_fold = (
            df[col_train] * w_train +
            df[col_valid] * w_valid +
            df[col_test]  * w_test
        ) / (w_train + w_valid + w_test)

        # Promedio total final entre folds
        resultados[m] = valores_fold.mean()

    return resultados

In [ ]:
if flag_baseline_metrics:
    print("flag_baseline_metrics=True → se omite el ponderado porque ya existe el dataset.")
else:
    print("flag_baseline_metrics=False → se inicia el ponderado")
    for k in k_folds:
        w = pesos_folds[k]

        # promedio ponderado para ESTE fold (sale como dict)
        res = weighted_avg_metrics_from_df(
            baseline_folds_metrics.loc[[f"baseline_fold_{k}"]],
            w["w_train"],
            w["w_valid"],
            w["w_test"]
        )

        # índice correspondiente en baseline_metrics
        idx = f"baseline_fold_{k}"

        # escribir directamente en el dataset transformers_metrics
        baseline_metrics.loc[idx, cols_base] = [res[m] for m in cols_base]

In [35]:
baseline_metrics

Empty DataFrame
Columns: [RMSE, MAE, R2, SMAPE, DirAcc]
Index: []

In [36]:
if flag_baseline_metrics == False:
  save_metrics(baseline_metrics,"6_catboost_model","1_baseline_metrics")
else:
  print("Ya existen métricas del entrenamiento y están guardadas en disco")

OSError: Cannot save file into a non-existent directory: '/content/drive/MyDrive/neural_profit/6_catboost_model/6_catboost_model'

Este punto existe para garantizar reproducibilidad y continuidad del análisis sin reentrenar modelos cuando se pierden las métricas. Actúa como fallback: reconstruye la tabla de métricas de Random Forest a partir de valores ya validados y la persiste nuevamente, evitando el re-entrenamiento de los modelos.

Así, se mantiene la consistencia de resultados y la trazabilidad de comparaciones y conclusiones, incluso si el archivo original fue eliminado, corrompido o el entorno de ejecución cambió.